# Generated by Django 5.1.3 on 2025-09-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='고객코드')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='상호')),
                ('rep', models.CharField(blank=True, max_length=20, null=True, verbose_name='대표자')),
                ('tel1', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화1')),
                ('tel3', models.CharField(blank=True, max_length=20, null=True, verbose_name='휴대전화')),
                ('enno', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자번호')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객목록',
                'db_table': 'customers_simple',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='상품코드')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('bun1', models.CharField(blank=True, max_length=50, null=True, verbose_name='브랜드')),
                ('jaego', models.IntegerField(default=0, verbose_name='재고수량')),
                ('fixp', models.BigIntegerField(default=0, verbose_name='고정가격')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='최종동기화')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품목록',
                'db_table': 'goods',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(max_length=20, verbose_name='상품코드')),
                ('year_2025', models.IntegerField(default=0, verbose_name='2025년')),
                ('year_2024', models.IntegerField(default=0, verbose_name='2024년')),
                ('year_2023', models.IntegerField(default=0, verbose_name='2023년')),
                ('year_2022', models.IntegerField(default=0, verbose_name='2022년')),
                ('year_2021_before', models.IntegerField(default=0, verbose_name='2021년 이전')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='최종수정')),
            ],
            options={
                'verbose_name': '연도별 할당',
                'verbose_name_plural': '연도별 할당목록',
                'db_table': 'year_allocations',
                'managed': True,
                'unique_together': {('goods_code',)},
            },
        ),
    ]
