# Generated by Django 5.1.3 on 2025-10-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='브랜드명')),
                ('group_name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('group_order', models.IntegerField(default=0, verbose_name='그룹 순서')),
                ('description', models.TextField(blank=True, null=True, verbose_name='그룹 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '브랜드 그룹',
                'verbose_name_plural': '브랜드 그룹 목록',
                'db_table': 'brand_groups',
                'ordering': ['brand', 'group_order', 'group_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrandGroupPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='패턴명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='tire_data.brandgroup', verbose_name='그룹')),
            ],
            options={
                'verbose_name': '그룹 패턴',
                'verbose_name_plural': '그룹 패턴 목록',
                'db_table': 'brand_group_patterns',
                'ordering': ['group', 'pattern'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10, verbose_name='고객 코드')),
                ('brand', models.CharField(max_length=50, verbose_name='브랜드명')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_discounts', to='tire_data.brandgroup', verbose_name='그룹')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='할인율(%)')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '고객 할인',
                'verbose_name_plural': '고객 할인 목록',
                'db_table': 'customer_discounts',
                'ordering': ['customer_code', 'brand', '-priority'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10, verbose_name='고객 코드')),
                ('product_code', models.CharField(max_length=50, verbose_name='상품 코드')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='브랜드')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tire_data.brandgroup', verbose_name='그룹')),
                ('basic_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='기본 할인율')),
                ('customer_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='고객 할인율')),
                ('applied_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='적용 할인율')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='원가')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='최종가격')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='거래일시')),
            ],
            options={
                'verbose_name': '할인 이력',
                'verbose_name_plural': '할인 이력 목록',
                'db_table': 'discount_history',
                'ordering': ['-transaction_date'],
                'managed': False,
            },
        ),
    ]
