# Generated by Django 5.1.3 on 2025-10-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0002_brandgroup_brandgrouppattern_customerdiscount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandgroup',
            options={'managed': True, 'ordering': ['brand', 'group_order', 'group_name'], 'verbose_name': '브랜드 그룹', 'verbose_name_plural': '브랜드 그룹 목록'},
        ),
        migrations.AlterModelOptions(
            name='brandgrouppattern',
            options={'managed': True, 'ordering': ['group', 'pattern'], 'verbose_name': '그룹 패턴', 'verbose_name_plural': '그룹 패턴 목록'},
        ),
        migrations.AlterModelOptions(
            name='customerdiscount',
            options={'managed': True, 'ordering': ['customer_code', 'brand', '-priority'], 'verbose_name': '고객 할인', 'verbose_name_plural': '고객 할인 목록'},
        ),
        migrations.AlterModelOptions(
            name='discounthistory',
            options={'managed': True, 'ordering': ['-transaction_date'], 'verbose_name': '할인 이력', 'verbose_name_plural': '할인 이력 목록'},
        ),
    ]
