# Generated by Django 5.1.3 on 2025-10-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0003_alter_brandgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10, verbose_name='고객 코드')),
                ('product_code', models.CharField(max_length=20, verbose_name='상품 코드')),
                ('additional_discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='추가 할인율(%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
            ],
            options={
                'db_table': 'customer_product_discounts',
                'managed': True,
                'unique_together': {('customer_code', 'product_code')},
            },
        ),
    ]
