# Generated by Django 5.1.3 on 2025-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0004_add_customer_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductdiscount',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='브랜드'),
        ),
    ]
