# Generated by Django 5.1.3 on 2025-10-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0006_erpsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': '주문', 'verbose_name_plural': '📊 판매 | 03. 주문'},
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='취소일시'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True, verbose_name='취소사유'),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='반품일시'),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_reason',
            field=models.TextField(blank=True, null=True, verbose_name='반품사유'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(
                choices=[
                    ('pending', '주문대기'),
                    ('confirmed', '주문확인'),
                    ('preparing', '출고준비'),
                    ('shipped', '배송중'),
                    ('delivered', '배송완료'),
                    ('cancelled', '주문취소'),
                    ('returned', '반품완료'),
                ],
                default='pending',
                max_length=20,
                verbose_name='주문상태'
            ),
        ),
    ]
