# Generated by Django 5.1.3 on 2025-10-23 07:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0008_excluded_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersFull',
            fields=[
                ('code', models.CharField(db_column='CODE', max_length=10, primary_key=True, serialize=False, verbose_name='고객코드')),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=100, null=True, verbose_name='상호')),
                ('rep', models.CharField(blank=True, db_column='REP', max_length=50, null=True, verbose_name='대표자')),
                ('tel1', models.CharField(blank=True, db_column='TEL1', max_length=20, null=True, verbose_name='전화1')),
                ('tel3', models.CharField(blank=True, db_column='TEL3', max_length=20, null=True, verbose_name='휴대전화')),
                ('tel4', models.CharField(blank=True, db_column='TEL4', max_length=20, null=True, verbose_name='전화4')),
                ('enno', models.CharField(blank=True, db_column='ENNO', max_length=20, null=True, verbose_name='사업자번호')),
                ('address1', models.CharField(blank=True, db_column='ADDRESS1', max_length=255, null=True, verbose_name='주소')),
                ('last_sync', models.DateTimeField(blank=True, db_column='LAST_SYNC', null=True, verbose_name='최종동기화')),
            ],
            options={
                'verbose_name': 'ERP 고객',
                'verbose_name_plural': 'ERP 고객목록',
                'db_table': 'customers',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsDisplayName',
            fields=[
                ('goods_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='상품코드')),
                ('korean_name', models.CharField(max_length=200, verbose_name='한글 상품명')),
                ('english_name', models.CharField(max_length=200, verbose_name='영문 상품명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '상품 표시명',
                'verbose_name_plural': 'C. ⚙️ 설정 | 04. 상품 표시명',
                'db_table': 'goods_display_names',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoodsPerformanceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(db_index=True, max_length=20, verbose_name='상품코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '상품 성능표기',
                'verbose_name_plural': 'C. ⚙️ 설정 | 01. 상품 성능표기',
                'db_table': 'goods_performance_tags',
                'ordering': ['goods_code', 'tag__category__order', 'tag__order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoodsRealtimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='상품코드')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('bun1', models.CharField(blank=True, max_length=100, null=True, verbose_name='브랜드')),
                ('jaego', models.IntegerField(verbose_name='재고수량')),
                ('snapshot_time', models.DateTimeField(db_index=True, verbose_name='스냅샷 시간')),
                ('change_from_prev', models.IntegerField(default=0, verbose_name='이전 대비 변화량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '실시간 재고 스냅샷',
                'verbose_name_plural': 'C. ⚙️ 설정 | 07. 실시간 재고 추적',
                'db_table': 'goods_realtime_snapshots',
                'ordering': ['-snapshot_time', 'code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerformanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('display_name', models.CharField(max_length=50, verbose_name='표시명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '성능표기 카테고리',
                'verbose_name_plural': 'C. ⚙️ 설정 | 02. 성능표기 카테고리',
                'db_table': 'performance_categories',
                'ordering': ['order', 'name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerformanceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '성능표기 태그',
                'verbose_name_plural': 'C. ⚙️ 설정 | 03. 성능표기 태그',
                'db_table': 'performance_tags',
                'ordering': ['category__order', 'category', 'order', 'name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ERPPhoneOrder',
            fields=[
            ],
            options={
                'verbose_name': 'ERP 전화주문',
                'verbose_name_plural': 'A. 📊 판매 | 02. ERP 전화주문',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tire_data.order',),
        ),
        migrations.CreateModel(
            name='MobileOrder',
            fields=[
            ],
            options={
                'verbose_name': '모바일 주문',
                'verbose_name_plural': 'A. 📊 판매 | 01. 모바일 주문',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tire_data.order',),
        ),
        migrations.AlterModelOptions(
            name='brandgroup',
            options={'managed': True, 'ordering': ['brand', 'group_order', 'group_name'], 'verbose_name': '브랜드 그룹', 'verbose_name_plural': 'B. 💰 할인 | 01. 브랜드 그룹'},
        ),
        migrations.AlterModelOptions(
            name='brandgrouppattern',
            options={'managed': True, 'ordering': ['group', 'pattern'], 'verbose_name': '그룹 패턴', 'verbose_name_plural': 'B. 💰 할인 | 02. 그룹 패턴'},
        ),
        migrations.AlterModelOptions(
            name='customerdiscount',
            options={'managed': True, 'ordering': ['customer_code', 'brand', '-priority'], 'verbose_name': '고객 할인', 'verbose_name_plural': 'B. 💰 할인 | 03. 고객별 할인'},
        ),
        migrations.AlterModelOptions(
            name='customerproductdiscount',
            options={'managed': True, 'ordering': ['customer_code', 'product_code', '-priority'], 'verbose_name': '고객별 상품 할인', 'verbose_name_plural': 'B. 💰 할인 | 04. 상품별 할인'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True, 'ordering': ['code'], 'verbose_name': '고객', 'verbose_name_plural': 'A. 📊 판매 | 02. 고객'},
        ),
        migrations.AlterModelOptions(
            name='discounthistory',
            options={'managed': True, 'ordering': ['-transaction_date'], 'verbose_name': '할인 이력', 'verbose_name_plural': 'B. 💰 할인 | 05. 할인 이력'},
        ),
        migrations.AlterModelOptions(
            name='erpsnapshot',
            options={'managed': True, 'ordering': ['-timestamp'], 'verbose_name': 'ERP 스냅샷', 'verbose_name_plural': 'C. ⚙️ 설정 | 06. ERP 스냅샷'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'managed': False, 'ordering': ['code'], 'verbose_name': '상품', 'verbose_name_plural': 'A. 📊 판매 | 01. 상품'},
        ),
        migrations.AlterModelOptions(
            name='yearallocation',
            options={'managed': True, 'verbose_name': '연식 할인율', 'verbose_name_plural': 'C. ⚙️ 설정 | 05. 연식 할인율'},
        ),
        migrations.RenameIndex(
            model_name='erpsnapshot',
            new_name='erp_snapsho_timesta_a4bd23_idx',
            old_name='erp_snapsho_timesta_04a836_idx',
        ),
        migrations.RenameIndex(
            model_name='erpsnapshot',
            new_name='erp_snapsho_status_d949ba_idx',
            old_name='erp_snapsho_status_9b3f52_idx',
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='tire_data.customers', verbose_name='고객'),
        ),
        migrations.AddField(
            model_name='yearallocation',
            name='base_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='상품기본할인(%)'),
        ),
        migrations.AddField(
            model_name='yearallocation',
            name='year_2021_before_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2021년 이전 할인율(%)'),
        ),
        migrations.AddField(
            model_name='yearallocation',
            name='year_2022_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2022년 할인율(%)'),
        ),
        migrations.AddField(
            model_name='yearallocation',
            name='year_2023_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2023년 할인율(%)'),
        ),
        migrations.AddField(
            model_name='yearallocation',
            name='year_2024_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2024년 할인율(%)'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='customer_code',
            field=models.CharField(max_length=10, verbose_name='고객 코드 (구버전, 사업자번호)'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='할인율(%)'),
        ),
        migrations.AlterField(
            model_name='customerproductdiscount',
            name='additional_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='추가 할인율(%)'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='applied_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='적용 할인율'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='basic_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='기본 할인율'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='customer_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='고객 할인율'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='최종가격'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='원가'),
        ),
        migrations.AlterField(
            model_name='yearallocation',
            name='year_2021_before',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2021년 이전 수량'),
        ),
        migrations.AlterField(
            model_name='yearallocation',
            name='year_2022',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2022년 수량'),
        ),
        migrations.AlterField(
            model_name='yearallocation',
            name='year_2023',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2023년 수량'),
        ),
        migrations.AlterField(
            model_name='yearallocation',
            name='year_2024',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2024년 수량'),
        ),
        migrations.AlterField(
            model_name='yearallocation',
            name='year_2025',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2025년 수량'),
        ),
        migrations.AlterUniqueTogether(
            name='brandgroup',
            unique_together={('brand', 'group_name')},
        ),
        migrations.AlterUniqueTogether(
            name='brandgrouppattern',
            unique_together={('group', 'pattern')},
        ),
        migrations.AlterUniqueTogether(
            name='customerdiscount',
            unique_together={('customer_code', 'brand', 'group')},
        ),
        migrations.AddIndex(
            model_name='goodsrealtimesnapshot',
            index=models.Index(fields=['code', '-snapshot_time'], name='goods_realt_code_f431cb_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsrealtimesnapshot',
            index=models.Index(fields=['-snapshot_time'], name='goods_realt_snapsho_8e65cb_idx'),
        ),
        migrations.AddField(
            model_name='performancetag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tire_data.performancecategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='goodsperformancetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_tags', to='tire_data.performancetag', verbose_name='성능표기'),
        ),
        migrations.AlterUniqueTogether(
            name='performancetag',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='goodsperformancetag',
            unique_together={('goods_code', 'tag')},
        ),
    ]
