# Generated by Django 5.1.3 on 2025-11-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0009_add_customer_fk_to_customerdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_column='customer_code', db_index=True, max_length=10, verbose_name='고객코드')),
                ('payment_type', models.CharField(choices=[('CARD', '신용/체크카드'), ('ACCOUNT', '계좌이체')], db_column='payment_type', max_length=10, verbose_name='결제수단유형')),
                ('billing_key', models.CharField(blank=True, db_column='billing_key', max_length=255, null=True, unique=True, verbose_name='빌링키')),
                ('card_company', models.CharField(blank=True, db_column='card_company', max_length=50, null=True, verbose_name='카드사')),
                ('card_last4', models.CharField(blank=True, db_column='card_last4', max_length=4, null=True, verbose_name='카드끝4자리')),
                ('card_type', models.CharField(blank=True, db_column='card_type', help_text='신용/체크/법인', max_length=20, null=True, verbose_name='카드종류')),
                ('account_bank', models.CharField(blank=True, db_column='account_bank', max_length=50, null=True, verbose_name='은행')),
                ('account_number_encrypted', models.CharField(blank=True, db_column='account_number_encrypted', max_length=255, null=True, verbose_name='계좌번호암호화')),
                ('account_last4', models.CharField(blank=True, db_column='account_last4', max_length=4, null=True, verbose_name='계좌끝4자리')),
                ('account_holder', models.CharField(blank=True, db_column='account_holder', max_length=50, null=True, verbose_name='예금주')),
                ('nickname', models.CharField(blank=True, db_column='nickname', help_text='예: 회사 법인카드, 개인 신한카드', max_length=50, null=True, verbose_name='별칭')),
                ('is_default', models.BooleanField(db_column='is_default', default=False, verbose_name='기본결제수단')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '결제수단',
                'verbose_name_plural': 'A. 📊 판매 | 03. 결제수단',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
                'managed': True,
            },
        ),
    ]
