# Generated by Django 5.1.3 on 2025-11-16 08:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0014_paymentmethod_customers_is_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='브랜드명')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='영문명')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': 'B. 💰 할인 | 01. 브랜드',
                'db_table': 'brands',
                'ordering': ['display_order', 'name'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='brandgroup',
            options={'managed': True, 'ordering': ['brand', 'group_order', 'group_name'], 'verbose_name': '브랜드 그룹', 'verbose_name_plural': 'Z. 🗄️ 미사용 | 01. 브랜드 그룹 (구)'},
        ),
        migrations.AlterModelOptions(
            name='brandgrouppattern',
            options={'managed': True, 'ordering': ['group', 'pattern'], 'verbose_name': '그룹 패턴', 'verbose_name_plural': 'Z. 🗄️ 미사용 | 02. 그룹 패턴 (구)'},
        ),
        migrations.AlterModelOptions(
            name='customerdiscount',
            options={'managed': True, 'ordering': ['customer_code', 'brand', '-priority'], 'verbose_name': '고객 할인', 'verbose_name_plural': 'Z. 🗄️ 미사용 | 03. 고객별 할인 (구)'},
        ),
        migrations.AlterModelOptions(
            name='customerproductdiscount',
            options={'managed': True, 'ordering': ['customer_code', 'product_code', '-priority'], 'verbose_name': '고객별 상품 할인', 'verbose_name_plural': 'B. 💰 할인 | 04. 개별 상품 할인'},
        ),
        migrations.AlterModelOptions(
            name='excludedgoods',
            options={'managed': True, 'verbose_name': '제외 상품', 'verbose_name_plural': 'C. ⚙️ 설정 | 09. ERP 동기화 제외 상품'},
        ),
        migrations.AlterModelOptions(
            name='yearallocation',
            options={'managed': True, 'verbose_name': '연식 할인율', 'verbose_name_plural': 'C. ⚙️ 설정 | 08. 연식 할인율'},
        ),
        migrations.AddField(
            model_name='customers',
            name='is_registered',
            field=models.BooleanField(db_column='is_registered', default=False, verbose_name='회원가입여부'),
        ),
        migrations.AddField(
            model_name='customers',
            name='must_change_password',
            field=models.BooleanField(db_column='must_change_password', default=True, verbose_name='비밀번호변경필요'),
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(blank=True, db_column='password', max_length=255, null=True, verbose_name='비밀번호'),
        ),
        migrations.AddField(
            model_name='customers',
            name='user_id',
            field=models.IntegerField(blank=True, db_column='user_id', null=True, verbose_name='사용자ID'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='code',
            field=models.CharField(db_column='code', max_length=10, primary_key=True, serialize=False, verbose_name='고객코드'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='enno',
            field=models.CharField(blank=True, db_column='enno', max_length=20, null=True, verbose_name='사업자번호'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=50, null=True, verbose_name='상호'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='rep',
            field=models.CharField(blank=True, db_column='rep', max_length=20, null=True, verbose_name='대표자'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tel1',
            field=models.CharField(blank=True, db_column='tel1', max_length=20, null=True, verbose_name='전화1'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tel3',
            field=models.CharField(blank=True, db_column='tel3', max_length=20, null=True, verbose_name='휴대전화'),
        ),
        migrations.CreateModel(
            name='BrandPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100, verbose_name='패턴명')),
                ('pattern_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='패턴 코드')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='tire_data.brand', verbose_name='브랜드')),
            ],
            options={
                'verbose_name': '브랜드 패턴',
                'verbose_name_plural': 'B. 💰 할인 | 02. 브랜드 패턴',
                'db_table': 'brand_patterns',
                'ordering': ['brand', 'display_order', 'pattern_name'],
                'managed': True,
                'unique_together': {('brand', 'pattern_name')},
            },
        ),
        migrations.CreateModel(
            name='BrandPatternPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, help_text='예: 전체, 승용세단, 승용SUV/RV, 트럭/밴, 스포츠카', max_length=50, null=True, verbose_name='분류1')),
                ('grade', models.CharField(blank=True, help_text='예: 전체, 가성비, 고급형, 최고급형, OE용타이어, 전기차', max_length=50, null=True, verbose_name='상품등급')),
                ('performance', models.CharField(blank=True, help_text='예: 전체, 스탠다드, 컴포트, 스포츠, 프리미엄스포츠', max_length=50, null=True, verbose_name='상품성능')),
                ('season', models.CharField(blank=True, help_text='예: 사계절용, 올웨더, 겨울용, 여름용', max_length=50, null=True, verbose_name='계절')),
                ('road_type', models.CharField(blank=True, help_text='예: 오프로드(MT), 온오프로드(AT), 온로드(HT)', max_length=50, null=True, verbose_name='ON/OFF로드')),
                ('logo_filename', models.CharField(blank=True, help_text='예: michelin.png (static/mobile/img/brands/ 경로)', max_length=100, null=True, verbose_name='로고 파일명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_settings', to='tire_data.brand', verbose_name='브랜드')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_settings', to='tire_data.brandpattern', verbose_name='패턴')),
            ],
            options={
                'verbose_name': '브랜드/패턴 성능표시',
                'verbose_name_plural': 'D. 📱 모바일 | 01. 브랜드/패턴 성능표시',
                'db_table': 'brand_pattern_performance',
                'ordering': ['brand', 'pattern'],
                'managed': True,
                'unique_together': {('brand', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='CustomerBrandDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='할인율(%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='생성자')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='수정자')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='tire_data.brand', verbose_name='브랜드')),
                ('customer', models.ForeignKey(db_column='customer_code', on_delete=django.db.models.deletion.CASCADE, related_name='brand_discounts', to='tire_data.customers', verbose_name='고객')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='tire_data.brandpattern', verbose_name='패턴')),
            ],
            options={
                'verbose_name': '고객별 브랜드 할인',
                'verbose_name_plural': 'B. 💰 할인 | 03. 고객별 할인',
                'db_table': 'customer_brand_discounts',
                'ordering': ['customer', 'brand', 'pattern', '-priority'],
                'managed': True,
                'unique_together': {('customer', 'brand', 'pattern')},
            },
        ),
    ]
