# Generated by Django 5.1.3 on 2025-11-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0015_brand_alter_brandgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpsnapshot',
            options={'managed': True, 'ordering': ['-timestamp'], 'verbose_name': 'ERP 스냅샷', 'verbose_name_plural': 'Z. 🗄️ 미사용 | ERP 스냅샷 (개발용)'},
        ),
        migrations.AlterModelOptions(
            name='excludedgoods',
            options={'managed': True, 'verbose_name': '제외 상품', 'verbose_name_plural': 'Z. 🗄️ 미사용 | ERP 동기화 제외 상품 (개발용)'},
        ),
        migrations.AlterModelOptions(
            name='goodsdisplayname',
            options={'managed': True, 'verbose_name': '상품 표시명', 'verbose_name_plural': 'C. ⚙️ 설정 | 01. 상품 표시명'},
        ),
        migrations.AlterModelOptions(
            name='goodsperformancetag',
            options={'managed': True, 'ordering': ['goods_code', 'tag__category__order', 'tag__order'], 'verbose_name': '상품 성능표기', 'verbose_name_plural': 'Z. 🗄️ 미사용 | 상품 성능표기 (구)'},
        ),
        migrations.AlterModelOptions(
            name='goodsrealtimesnapshot',
            options={'managed': True, 'ordering': ['-snapshot_time', 'code'], 'verbose_name': '실시간 재고 스냅샷', 'verbose_name_plural': 'Z. 🗄️ 미사용 | 실시간 재고 추적 (개발용)'},
        ),
        migrations.AlterModelOptions(
            name='performancecategory',
            options={'managed': True, 'ordering': ['order', 'name'], 'verbose_name': '성능표기 카테고리', 'verbose_name_plural': 'Z. 🗄️ 미사용 | 성능표기 카테고리 (구)'},
        ),
        migrations.AlterModelOptions(
            name='performancetag',
            options={'managed': True, 'ordering': ['category__order', 'category', 'order', 'name'], 'verbose_name': '성능표기 태그', 'verbose_name_plural': 'Z. 🗄️ 미사용 | 성능표기 태그 (구)'},
        ),
        migrations.AlterModelOptions(
            name='yearallocation',
            options={'managed': True, 'verbose_name': '연식 할인율', 'verbose_name_plural': 'C. ⚙️ 설정 | 02. 연도 할당률 (DOT)'},
        ),
        migrations.AddField(
            model_name='customers',
            name='membership_tier',
            field=models.CharField(choices=[('regular', '🎫 일반 회원'), ('premium', '⭐ 프리미엄 회원')], db_column='membership_tier', default='regular', help_text='간편결제 사용 시 프리미엄 회원으로 자동 승급', max_length=20, verbose_name='회원등급'),
        ),
        migrations.AddField(
            model_name='customers',
            name='tier_updated_at',
            field=models.DateTimeField(blank=True, db_column='tier_updated_at', null=True, verbose_name='등급갱신일'),
        ),
    ]
