# Generated by Django 5.1.3 on 2025-11-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0016_alter_erpsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandpatternperformance',
            options={'managed': True, 'ordering': ['brand', 'pattern'], 'verbose_name': '브랜드/패턴 성능표시', 'verbose_name_plural': 'B. 💰 할인 | 05. 브랜드/패턴 성능표시'},
        ),
    ]
