# Generated by Django 5.1.3 on 2025-11-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0017_alter_brandpatternperformance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandpatternperformance',
            options={'managed': True, 'ordering': ['brand', 'pattern'], 'verbose_name': '브랜드/패턴 성능표시', 'verbose_name_plural': 'C. ⚙️ 설정 | 03. 브랜드/패턴 성능표시'},
        ),
    ]
