# Generated by Django 5.1.3 on 2025-11-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0020_alter_brandpatternperformance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpattern',
            name='classification',
            field=models.CharField(blank=True, help_text='예: 전체, 승용세단, 승용SUV/RV, 트럭/밴, 스포츠카', max_length=50, null=True, verbose_name='분류1'),
        ),
        migrations.AddField(
            model_name='brandpattern',
            name='grade',
            field=models.CharField(blank=True, help_text='예: 전체, 가성비, 고급형, 최고급형, OE용타이어, 전기차', max_length=50, null=True, verbose_name='상품등급'),
        ),
        migrations.AddField(
            model_name='brandpattern',
            name='logo_filename',
            field=models.CharField(blank=True, help_text='예: michelin.png (static/mobile/img/brands/ 경로)', max_length=100, null=True, verbose_name='브랜드 로고 파일명'),
        ),
        migrations.AddField(
            model_name='brandpattern',
            name='performance',
            field=models.CharField(blank=True, help_text='예: 정숙성, 주행안정성, 젖은노면제동력, 연비, 구름저항, 마일리지', max_length=50, null=True, verbose_name='상품성능'),
        ),
        migrations.AddField(
            model_name='brandpattern',
            name='road_type',
            field=models.CharField(blank=True, help_text='예: ON로드, OFF로드', max_length=20, null=True, verbose_name='로드타입'),
        ),
        migrations.AddField(
            model_name='brandpattern',
            name='season',
            field=models.CharField(blank=True, help_text='예: 사계절, 겨울용, 여름용', max_length=20, null=True, verbose_name='계절'),
        ),
    ]
