# Generated by Django 5.1.3 on 2025-11-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0021_add_performance_fields_to_brandpattern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandPatternPerformance',
        ),
    ]
