# Generated by Django 5.1.3 on 2025-11-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tire_data", "0022_remove_brandpatternperformance_add_performance_to_brandpattern"),
    ]

    operations = []