# Generated by Django 5.1.3 on 2025-11-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0023_merge_20251117_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='정책명')),
                ('earn_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='결제 금액의 몇 %를 포인트로 적립할지 (예: 1.0 = 1%)', max_digits=5, verbose_name='적립률 (%)')),
                ('min_order_amount', models.IntegerField(default=0, help_text='이 금액 이상 주문 시에만 포인트 적립', verbose_name='최소 주문 금액')),
                ('signup_bonus', models.IntegerField(default=0, help_text='회원가입 시 지급할 포인트', verbose_name='회원가입 보너스')),
                ('point_validity_days', models.IntegerField(default=365, help_text='포인트 적립 후 며칠간 사용 가능한지', verbose_name='포인트 유효기간 (일)')),
                ('min_use_amount', models.IntegerField(default=1000, help_text='한 번에 사용 가능한 최소 포인트', verbose_name='최소 사용 포인트')),
                ('max_use_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='주문 금액의 최대 몇 %까지 포인트로 결제 가능한지', max_digits=5, verbose_name='최대 사용 비율 (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '포인트 정책',
                'verbose_name_plural': 'C. ⚙️ 설정 | 05. 포인트 정책',
                'db_table': 'point_policies',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='brandpattern',
            name='logo_filename',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='브랜드 로고 이미지를 업로드하세요 (PNG, JPG 권장)', null=True, upload_to='brands/logos/', verbose_name='브랜드 로고 이미지'),
        ),
        migrations.AlterField(
            model_name='brandpattern',
            name='classification',
            field=models.CharField(blank=True, choices=[('', '--------'), ('전체', '전체'), ('승용세단', '승용세단'), ('승용SUV/RV', '승용SUV/RV'), ('트럭/밴', '트럭/밴'), ('스포츠카', '스포츠카')], max_length=50, null=True, verbose_name='분류1'),
        ),
        migrations.AlterField(
            model_name='brandpattern',
            name='grade',
            field=models.CharField(blank=True, choices=[('', '--------'), ('전체', '전체'), ('가성비', '가성비'), ('고급형', '고급형'), ('최고급형', '최고급형'), ('OE용타이어', 'OE용타이어'), ('전기차', '전기차')], max_length=50, null=True, verbose_name='상품등급'),
        ),
        migrations.AlterField(
            model_name='brandpattern',
            name='performance',
            field=models.CharField(blank=True, choices=[('', '--------'), ('전체', '전체'), ('스탠다드', '스탠다드'), ('컴포트', '컴포트'), ('스포츠', '스포츠'), ('프리미엄스포츠', '프리미엄스포츠')], max_length=50, null=True, verbose_name='상품성능'),
        ),
        migrations.AlterField(
            model_name='brandpattern',
            name='road_type',
            field=models.CharField(blank=True, choices=[('', '--------'), ('오프로드(MT)', '오프로드(MT)'), ('온오프로드(AT)', '온오프로드(AT)'), ('온로드(HT)', '온로드(HT)')], max_length=20, null=True, verbose_name='ON/OFF로드'),
        ),
        migrations.AlterField(
            model_name='brandpattern',
            name='season',
            field=models.CharField(blank=True, choices=[('', '--------'), ('사계절용', '사계절용'), ('올웨더', '올웨더'), ('겨울용', '겨울용'), ('여름용', '여름용')], max_length=20, null=True, verbose_name='계절'),
        ),
        migrations.CreateModel(
            name='CustomerPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='포인트 잔액')),
                ('total_earned', models.IntegerField(default=0, verbose_name='누적 적립 포인트')),
                ('total_used', models.IntegerField(default=0, verbose_name='누적 사용 포인트')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_points', to='tire_data.customers', verbose_name='고객')),
            ],
            options={
                'verbose_name': '고객 포인트',
                'verbose_name_plural': 'A. 📊 판매 | 03. 고객 포인트',
                'db_table': 'customer_points',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN_ORDER', '주문 적립'), ('EARN_SIGNUP', '회원가입 적립'), ('EARN_EVENT', '이벤트 적립'), ('EARN_ADMIN', '관리자 지급'), ('USE', '포인트 사용'), ('EXPIRE', '포인트 만료'), ('CANCEL', '적립 취소')], max_length=20, verbose_name='거래 유형')),
                ('amount', models.IntegerField(verbose_name='포인트 금액')),
                ('balance_after', models.IntegerField(verbose_name='거래 후 잔액')),
                ('description', models.CharField(max_length=200, verbose_name='설명')),
                ('order_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='주문번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='거래일시')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='tire_data.customers', verbose_name='고객')),
            ],
            options={
                'verbose_name': '포인트 거래 내역',
                'verbose_name_plural': 'A. 📊 판매 | 04. 포인트 거래 내역',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['customer', '-created_at'], name='point_trans_custome_09f349_idx'), models.Index(fields=['order_code'], name='point_trans_order_c_bbd358_idx')],
            },
        ),
    ]
