# Generated by Django 5.1.3 on 2025-11-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tire_data", "0022_merge_20251117_1459"),
        ("tire_data", "0025_remove_brand_logo_filename_brand_logo_image_and_more"),
    ]

    operations = []
