# Generated by Django 5.1.3 on 2025-11-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tire_data", "0023_merge_20251117_1557"),
        ("tire_data", "0024_add_point_system"),
    ]

    operations = []
