# Generated by Django 5.1.3 on 2025-12-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire_data', '0028_add_policy_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpoint',
            options={'managed': True, 'verbose_name': '고객 포인트', 'verbose_name_plural': 'C. ⚙️ 설정 | 03. 고객 포인트'},
        ),
        migrations.AlterModelOptions(
            name='pointtransaction',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': '포인트 거래 내역', 'verbose_name_plural': 'C. ⚙️ 설정 | 04. 포인트 거래 내역'},
        ),
        migrations.AlterModelOptions(
            name='policypage',
            options={'managed': True, 'ordering': ['display_order', 'title'], 'verbose_name': '정책 페이지', 'verbose_name_plural': 'C. ⚙️ 설정 | 10. 정책 페이지 관리'},
        ),
        migrations.AddField(
            model_name='customerproductdiscount',
            name='customer_name',
            field=models.CharField(blank=True, help_text='고객의 상호명을 입력하세요', max_length=100, null=True, verbose_name='고객명/상호'),
        ),
        migrations.AlterField(
            model_name='customerproductdiscount',
            name='customer_code',
            field=models.CharField(help_text='ERP 고객코드 형식: 0-0-0000 (예: 0-0-0002)', max_length=20, verbose_name='고객 코드'),
        ),
    ]
