/*
==================================================
Firebird ERP 서버 - 실시간 동기화 트리거 설치
==================================================

광주 ERP 서버(ITIRE.GDB)에서 실행할 SQL

1. 변경 로그 테이블 생성
2. CUSTOMS/GOODS 테이블에 트리거 설치
3. 변경 발생 시 로그 테이블에 기록
*/

-- ============================================
-- 1. 변경 로그 테이블 생성
-- ============================================

CREATE TABLE SYNC_LOG (
    LOG_ID INTEGER NOT NULL,
    TABLE_NAME VARCHAR(50) NOT NULL,
    OPERATION VARCHAR(10) NOT NULL,  /* INSERT, UPDATE, DELETE */
    RECORD_KEY VARCHAR(50) NOT NULL,  /* CODE 값 */
    CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SYNC_STATUS VARCHAR(20) DEFAULT 'PENDING',  /* PENDING, SENT, ERROR */
    ERROR_MESSAGE VARCHAR(500),
    RETRY_COUNT INTEGER DEFAULT 0,
    PRIMARY KEY (LOG_ID)
);

CREATE GENERATOR GEN_SYNC_LOG_ID;
SET GENERATOR GEN_SYNC_LOG_ID TO 0;

CREATE INDEX IDX_SYNC_LOG_STATUS ON SYNC_LOG(SYNC_STATUS);
CREATE INDEX IDX_SYNC_LOG_TABLE ON SYNC_LOG(TABLE_NAME);
CREATE INDEX IDX_SYNC_LOG_CHANGED_AT ON SYNC_LOG(CHANGED_AT);

-- ============================================
-- 2. CUSTOMS 테이블 트리거
-- ============================================

SET TERM ^ ;

-- CUSTOMS INSERT 트리거
CREATE TRIGGER TRG_CUSTOMS_AI FOR CUSTOMS
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
    INSERT INTO SYNC_LOG (LOG_ID, TABLE_NAME, OPERATION, RECORD_KEY, CHANGED_AT)
    VALUES (GEN_ID(GEN_SYNC_LOG_ID, 1), 'CUSTOMS', 'INSERT', NEW.CODE, CURRENT_TIMESTAMP);
END^

-- CUSTOMS UPDATE 트리거
CREATE TRIGGER TRG_CUSTOMS_AU FOR CUSTOMS
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
    INSERT INTO SYNC_LOG (LOG_ID, TABLE_NAME, OPERATION, RECORD_KEY, CHANGED_AT)
    VALUES (GEN_ID(GEN_SYNC_LOG_ID, 1), 'CUSTOMS', 'UPDATE', NEW.CODE, CURRENT_TIMESTAMP);
END^

-- CUSTOMS DELETE 트리거
CREATE TRIGGER TRG_CUSTOMS_AD FOR CUSTOMS
ACTIVE AFTER DELETE POSITION 0
AS
BEGIN
    INSERT INTO SYNC_LOG (LOG_ID, TABLE_NAME, OPERATION, RECORD_KEY, CHANGED_AT)
    VALUES (GEN_ID(GEN_SYNC_LOG_ID, 1), 'CUSTOMS', 'DELETE', OLD.CODE, CURRENT_TIMESTAMP);
END^

-- ============================================
-- 3. GOODS 테이블 트리거
-- ============================================

-- GOODS INSERT 트리거
CREATE TRIGGER TRG_GOODS_AI FOR GOODS
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
    INSERT INTO SYNC_LOG (LOG_ID, TABLE_NAME, OPERATION, RECORD_KEY, CHANGED_AT)
    VALUES (GEN_ID(GEN_SYNC_LOG_ID, 1), 'GOODS', 'INSERT', NEW.CODE, CURRENT_TIMESTAMP);
END^

-- GOODS UPDATE 트리거
CREATE TRIGGER TRG_GOODS_AU FOR GOODS
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
    INSERT INTO SYNC_LOG (LOG_ID, TABLE_NAME, OPERATION, RECORD_KEY, CHANGED_AT)
    VALUES (GEN_ID(GEN_SYNC_LOG_ID, 1), 'GOODS', 'UPDATE', NEW.CODE, CURRENT_TIMESTAMP);
END^

-- GOODS DELETE 트리거
CREATE TRIGGER TRG_GOODS_AD FOR GOODS
ACTIVE AFTER DELETE POSITION 0
AS
BEGIN
    INSERT INTO SYNC_LOG (LOG_ID, TABLE_NAME, OPERATION, RECORD_KEY, CHANGED_AT)
    VALUES (GEN_ID(GEN_SYNC_LOG_ID, 1), 'GOODS', 'DELETE', OLD.CODE, CURRENT_TIMESTAMP);
END^

SET TERM ; ^

-- ============================================
-- 4. 트리거 확인
-- ============================================

SELECT
    RDB$TRIGGER_NAME,
    RDB$RELATION_NAME,
    RDB$TRIGGER_TYPE,
    RDB$TRIGGER_INACTIVE
FROM RDB$TRIGGERS
WHERE RDB$RELATION_NAME IN ('CUSTOMS', 'GOODS')
  AND RDB$SYSTEM_FLAG = 0
ORDER BY RDB$RELATION_NAME, RDB$TRIGGER_NAME;

COMMIT;
