/**
 * 긴급: ERP 트리거 비활성화 스크립트
 *
 * 실행 방법:
 *   1. 명령 프롬프트 관리자 권한 실행
 *   2. cd "C:\Program Files (x86)\Firebird\Firebird_2_5\bin"
 *   3. isql -user SYSDBA -password masterkey "C:\Program Files\PsimCarS\Data\ITIRE.GDB" -i "C:\Users\jmyang\Dropbox\1.0_tirepass\rollback_triggers.sql"
 */

/* 트리거 비활성화 */
ALTER TRIGGER TRG_CUSTOMS_AI INACTIVE;
ALTER TRIGGER TRG_CUSTOMS_AU INACTIVE;
ALTER TRIGGER TRG_CUSTOMS_AD INACTIVE;
ALTER TRIGGER TRG_GOODS_AI INACTIVE;
ALTER TRIGGER TRG_GOODS_AU INACTIVE;
ALTER TRIGGER TRG_GOODS_AD INACTIVE;
COMMIT;

/* 상태 확인 */
SELECT 'Trigger Status:' AS INFO FROM RDB$DATABASE;
SELECT
    RDB$TRIGGER_NAME AS TRIGGER_NAME,
    RDB$RELATION_NAME AS TABLE_NAME,
    CASE RDB$TRIGGER_INACTIVE
        WHEN 0 THEN 'ACTIVE'
        WHEN 1 THEN 'INACTIVE'
    END AS STATUS
FROM RDB$TRIGGERS
WHERE RDB$RELATION_NAME IN ('CUSTOMS', 'GOODS')
  AND RDB$SYSTEM_FLAG = 0
ORDER BY RDB$RELATION_NAME, RDB$TRIGGER_NAME;
